Upgradeability
Kwenta/KSX pull request #1
Opened 2024-06-12 16:59 UTC by Flocqst

Make KSXVault UUPSUpgradeable

## Description
* Used OpenZeppelin UUPSUpgradeable pattern
* Vault is only upgradeable by pDAO address (can be set to 0 to make contract non upgradeable)

## Motivation and Context
https://github.com/Kwenta/kwenta-state-log/blob/master/kips/kip-123.md
> $KSX will be upgradable to allow future changes to the staking strategy and composition of the backing tokens.

2024-06-24 17:52 UTC, jcmonte commented on script/Deploy.s.sol
> +contract DeployOptimism_Synthetix is Setup, OptimismParameters {
copy pasta? not sure the relation to synthetix

2024-06-24 17:52 UTC, jcmonte commented on src/KSXVault.sol
> +    function _authorizeUpgrade(address /* _newImplementation */ )
missing functionality? the parameter is commented out

2024-06-24 17:52 UTC, jcmonte commented on test/Upgrade.t.sol
> +        // vm.rollFork(BASE_BLOCK_NUMBER);
commented code, still needed?

2024-06-24 17:53 UTC, jcmonte commented
@JaredBorders Can I get your experienced review here - context is KSX vault and adding upgradeability

2024-06-24 18:06 UTC, Flocqst commented on script/Deploy.s.sol
> +contract DeployOptimism_Synthetix is Setup, OptimismParameters {
Yes, coming from smart margin deploy scripts, will change

2024-06-24 18:12 UTC, Flocqst commented on src/KSXVault.sol
> +    function _authorizeUpgrade(address /* _newImplementation */ )
It is intentionally commented out to maintain interface compliance

2024-06-24 18:12 UTC, Flocqst commented on test/Upgrade.t.sol
> +        // vm.rollFork(BASE_BLOCK_NUMBER);
Removed

2024-09-05 01:22 UTC, jcmonte requested changes

2024-09-05 01:22 UTC, jcmonte commented on test/Upgrade.t.sol
> +    }
Should also test that initializer is disabled after first deployment

2024-09-05 01:22 UTC, jcmonte commented on src/KSXVault.sol
> +        _disableInitializers();
Does this work? Won't this disable the initializer before it's ever called?

2024-09-11 13:26 UTC, Flocqst commented on src/KSXVault.sol
> +        _disableInitializers();
Yes this works, this is just to prevent **_implementation_** contract from being initialized, while the proxy will still use initializer.

2024-09-11 20:10 UTC, jcmonte approved these changes

2024-09-13 14:42 UTC, merged